package com.laomn.dao;

import com.laomn.entites.Test123;

public interface Test123Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test123
     *
     * @mbggenerated Wed Aug 01 16:16:24 CST 2018
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test123
     *
     * @mbggenerated Wed Aug 01 16:16:24 CST 2018
     */
    int insert(Test123 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test123
     *
     * @mbggenerated Wed Aug 01 16:16:24 CST 2018
     */
    int insertSelective(Test123 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test123
     *
     * @mbggenerated Wed Aug 01 16:16:24 CST 2018
     */
    Test123 selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test123
     *
     * @mbggenerated Wed Aug 01 16:16:24 CST 2018
     */
    int updateByPrimaryKeySelective(Test123 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test123
     *
     * @mbggenerated Wed Aug 01 16:16:24 CST 2018
     */
    int updateByPrimaryKey(Test123 record);
}