package com.laomn.entites;

public class Test123 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test123.code
     *
     * @mbggenerated Wed Aug 01 16:16:24 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test123.name1
     *
     * @mbggenerated Wed Aug 01 16:16:24 CST 2018
     */
    private String name1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test123.age
     *
     * @mbggenerated Wed Aug 01 16:16:24 CST 2018
     */
    private Integer age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test123.code
     *
     * @return the value of test123.code
     *
     * @mbggenerated Wed Aug 01 16:16:24 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test123.code
     *
     * @param code the value for test123.code
     *
     * @mbggenerated Wed Aug 01 16:16:24 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test123.name1
     *
     * @return the value of test123.name1
     *
     * @mbggenerated Wed Aug 01 16:16:24 CST 2018
     */
    public String getName1() {
        return name1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test123.name1
     *
     * @param name1 the value for test123.name1
     *
     * @mbggenerated Wed Aug 01 16:16:24 CST 2018
     */
    public void setName1(String name1) {
        this.name1 = name1 == null ? null : name1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test123.age
     *
     * @return the value of test123.age
     *
     * @mbggenerated Wed Aug 01 16:16:24 CST 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test123.age
     *
     * @param age the value for test123.age
     *
     * @mbggenerated Wed Aug 01 16:16:24 CST 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }
}